### ISSUE TITLE
Alpha channel is needed

### ISSUE THREAD

**Issue by ClassWizard** [dorukgunes/zeplin-color-spaces-extension#1]
For colors like “#00000080”, the alpha channel is ignored. Want to be able to have opacity of display, for example, "rgb": "0 0 0 0.5"

**Comment by dorukgunes** [comment]
Sorry for the late reply @ClassWizard, in the following I changed the `rgb` to `rgba` which you can see the opacity from now on. Make sure you use the extension version >= 1.1.0. Please reopen this issue if it does not solve your issue.

https://github.com/dorukgunes/zeplin-color-spaces-extension/commit/d697dcf2e01e1bbc36a7414c2b0517d80b093cd7
